CREATE TABLE IF NOT EXISTS avion (
	AvNum INT PRIMARY KEY NOT NULL,
	AvNom VARCHAR(20),
	Capacite INT,
	Localisation VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS pilote (
	PINum INT PRIMARY KEY NOT NULL,
	PINom VARCHAR(20),
	PIPrenom VARCHAR(20),
	Ville VARCHAR(20),
	Salaire INT
);

CREATE TABLE IF NOT EXISTS vol (
	VolNum INT PRIMARY KEY NOT NULL,
	PINum INT,
	FOREIGN KEY(PINum) REFERENCES pilote(PINum),
	AvNum INT,
	FOREIGN KEY(AvNum) REFERENCES avion(AvNum),
	VilleDep VARCHAR(20),
	VilleArr VARCHAR(20),
	HeureDep TIME,
	HeureArr TIME
);
